services:
  nginx:
    build: .
    container_name: note
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web

networks:
  web:
    external: true
